### ISSUE TITLE
CoAP: Retransmit counter exceeded

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-coap-client#16]
I am calling `node-coap-client` in a `setInterval()` on a number of devices to watch for changes.  Is there a better way?

The lowest level calling code is on the lines of:

```javascript
      GET(url) { // Returns a promise
        return Coap.request(url, 'get', {
          keepAlive: true,
          confirmable: false,
          observe: false,
          retransmit: false
        }).then(function(result) {
          return JSON.parse(result.payload.toString());
        });
      }
```

however, eventually I will catch an error of `Error: Retransmit counter exceeded`.  But with `retransmit:false` I'm surprised this can happen.  Am I missing something?

I don't really understand the documentation around the options and `retransmit` seems to be undocumented.  Could you explain how they work?

Thanks.

**Comment by AlCalzone** [comment]
Hey, thanks for asking. I really need to update the documentation.

If you are passing options but not a payload, you have to specifically pass null as the 3rd parameter. Also there's no observe property in the options object anymore. 
```
Coap.request(url, 'get', null, {
	keepAlive: true,
	confirmable: false,
	retransmit: false
}
```

I'm not exactly sure what you are trying to do, but it seems like observing the resource would be better. This automatically calls a provided callback whenever a resource has some changes.
```
Coap.observe(url, 'get',
    (response => /* called on update */),
    payload,
    options
);
```
Coap observe itself is a promise that returns when the original request has been received.

Or are you just trying to check if a device is there or not? Manually setting `confirmable=false` and `retransmit=false` seems unconventional. In this case you might want to `ping` the device:
```
Coap.ping(url, 
    timeout // optional, default 5000ms
).then(success => /* true or false */);
```

**Comment by AlCalzone** [comment]
Please check if the updated documentation makes things more clear.

**Comment by CliffS** [comment]
> Please check if the updated documentation makes things more clear.

Well, with some documentation, It's like using a different library. :)

I'm off to throw away all my code and rewrite it now I understand what's going on.

Thanks.

**Comment by AlCalzone** [comment]
Sorry for the hassle then :) Closing.
