### ISSUE TITLE
request() returns too fast

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-coap-client#19]
`CoapClient.request()` sends the message to the controller and resolves the promise.

The problem is that at this point, the controller is not ready for the next request so requests sent quickly may get lost.

Is there any way to ensure that the controller is ready for the next request before resolving the current one?

**Comment by AlCalzone** [comment]
Actually, the promise should only be resolved after an ACK from the gateway was received. In addition, there is a queue in place which limits the number of concurrent requests.

Can you provide a debug log where a request gets lost? (See the open issue in node-tradfri-client for a howto)

**Comment by CliffS** [comment]
Looking at the code, I must be misunderstanding something.  Please bear in mind that I don't know Typescript so that's probably what's causing me the confusion.

It seems to me that when messages come in faster than the controller can handle them, they get queued by `CoapClient.send()`.  However this then returns to `CoapClient.request()` which returns to the caller, even though the message may not actually be sent out until 1s later.  What am I missing?

**Comment by AlCalzone** [comment]
`CoapClient.request` creates a promise (actually a `DeferredPromise`) [in Line 303](https://github.com/AlCalzone/node-coap-client/blob/master/src/CoapClient.ts#L303) which it returns immediately.
In the `onMessage` method, that promise is resolved ([Line 592](https://github.com/AlCalzone/node-coap-client/blob/master/src/CoapClient.ts#L592) or [Line 641](https://github.com/AlCalzone/node-coap-client/blob/master/src/CoapClient.ts#L641)), but **only after** either the `ACK` or the piggybacked response from the gateway was received.

**Comment by CliffS** [comment]
OK, thanks.  I see that now.  Very neat.  I'll stop blaming your code and try to fix the problem in mine. :)

I think my issue is that the bulbs do not respond if they are already in transition.  So if, for example, I send `{ colorTemperature: 97 }' followed by '{ onOff: false }' in quick succession, the bulb stays on.  I'll try to set up a simple test case for this.  In the meanwhile I'm closing this issue as the problem is not at this level.

**Comment by AlCalzone** [comment]
I see. I should be able to reproduce that issue on my own, but you‘re probably quicker.

**Comment by CliffS** [comment]
I don't seem to be able to reproduce it using only the node-tradfri-client library.  Clearly something wrong with my code.  Thanks again for your help.
