### ISSUE TITLE
Observe Length cannot be 0

### ISSUE THREAD

**Issue by holomekc** [AlCalzone/node-coap-client#239]
Due to the current implementation it is not possible to set no content for the Observe Option. Currently I have one communication partner which does not accept that:
![image](https://user-images.githubusercontent.com/30546982/80274805-49118200-86dd-11ea-84e6-10bef2bd2242.png)

In the specification it looks like it is allowed to have no content:
https://tools.ietf.org/html/rfc7641#section-2

This works for me:
![image](https://user-images.githubusercontent.com/30546982/80274868-ee2c5a80-86dd-11ea-9680-214f71da9f38.png)

A possible solution would be that it is allowed to specify the actual value instead of always true -> 0
Or even better to allow overwriting the Options properties. E.g. by a new function which allows to specify the Buffers.from() part of Options in Option.ts

My solution is quite hacky because I overwrite exports.Options completely and 
specified:
```TypeScript
Observe: (observe: boolean) => optionConstructors["Observe"](Buffer.from(observe ? '' : '1')),
```

I am not sure regarding deregister. stopObserving() does not send a message as far as I could see it.

**Comment by AlCalzone** [comment]
According to https://tools.ietf.org/html/rfc7641#section-3.6, the deregister is optional. The option length of 1 was a bug, because I did not use the `numberToBuffer` helper in the observe option which automatically makes the buffer as short as possible.

The next patch is on its way, thanks for the report!
