### ISSUE TITLE
URL parsing in a browser context

### ISSUE THREAD

**Issue by DavidMulder0** [AlCalzone/node-coap-client#248]
In [Origin.ts:10](https://github.com/AlCalzone/node-coap-client/blob/master/src/lib/Origin.ts#L10) you use `if (!global.URL) {` meaning that in a shared node and browser context (e.g. electron) you use [the global `URL` object](https://developer.mozilla.org/en/docs/Web/API/URL). This URL object isn't able to parse unknown protocols, so if you for example run `(new URL('coaps://www.google.com')).hostname;` in the browser console it will return an empty string. Simply always using the node URL module will solve this issue.

**Comment by AlCalzone** [comment]
This will be changed in v1.0.7 (on npm in a couple of minutes)
