### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by bobrik** [AlCalzone/node-coap-client#39]
I'm trying to use `homebridge-ikea-tradfri-gateway` and as any reasonable human in 2019, I have Tradfri gateway on a sateless IPv6 SLAAC address. Sadly, it doesn't work:

```
[3/24/2019, 6:25:12 PM] [Ikea Trådfri Gateway] Initializing Ikea Trådfri Gateway platform...
[3/24/2019, 6:25:12 PM] [Ikea Trådfri Gateway] didFinishLaunching
{ Error: The gateway did not respond in time.
    at TradfriClient.<anonymous> (/usr/local/lib/node_modules/homebridge-ikea-tradfri-gateway/node_modules/node-tradfri-client/build/tradfri-client.js:179:39)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ikea-tradfri-gateway/node_modules/node-tradfri-client/build/tradfri-client.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 1 }
```

After looking around a bit I discovered that only `A` record is queried during initialization, presumably because `udp4` dgram socket is being used here:

* https://github.com/AlCalzone/node-coap-client/blob/715aaceba18/src/CoapClient.ts#L1185

I can hack around it with `sed -i 's/udp4/udp6/g' /path/to/CoapClient.js`.

**Comment by AlCalzone** [comment]
Thanks for the report. Just a few questions to figure out how to best fix this...
* Are you passing a hostname or IP address to the library?
* Is it obvious from the gateway address that it is responding to IPv6?
* Does the library behave as expected when using udp6 sockets (after your fix)?

**Comment by bobrik** [comment]
> Are you passing a hostname or IP address to the library?

I am passing a hostname that only has AAAA records.

> Is it obvious from the gateway address that it is responding to IPv6?

It only has AAAA record, so I would say yes. I'm not sure if there's a better fix for stateless UDP than:

1. Resolve address if it's a hostname.
2. Loop through IPs and try to authenticate with each one with appropriate protocol (udp4 or udp6).

> Does the library behave as expected when using udp6 sockets (after your fix)?

Yes, it works as expected, I can flip my outlet on and off via homebridge.

**Comment by AlCalzone** [comment]
@bobrik I have a branch up at https://github.com/AlCalzone/node-coap-client/tarball/ipv6
Can you please try to install that version as a dependency in your project and see if it works?
Unfortunately, my gateway does not respond to the IPv6 connection attempts so I cannot test myself.

The library now uses `udp6` as the socket type if the address is a valid IPv6 address. It does not perform any host name lookup yet. You might have to configure your library or whatever to use the IPv6 address directly. Let me know if that works.

**Comment by dgtlrift** [comment]
Is there a way to address link-local addresses with scope? It seems that this is undefined in general, but I've seen a pattern [fe80::Xxx]%[scope] referenced here https://ungleich.ch/u/blog/ipv6-link-local-support-in-browsers/
